name: Setup OpenJDK 11

on:
  push:
    branches:
      - main  # Replace with your branch name if different
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up OpenJDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Eclipse Temurin is a popular OpenJDK distribution
          java-version: '11'

      - name: Verify Java installation
        run: java -version
